### ISSUE TITLE
 [Orchid] wrong keyboard layout at boot time : hard to type the password to decrypt the disk

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/ABRoot#201] opened 2024-01-12 10:44 UTC
Issue Description

At first reboot (after install), it's hard to type the password to decrypt the hdd as the keyboard layout is set to US by default.
Steps to Reproduce

- At installation time, I chose a keyboard layout (not US) and I decided to encrypt my hdd.
- Installation succeeded and the vm rebooted.
- At reboot it ask for my password to decrypt my hdd.
- The keyboard layout is US so it makes it difficult to type my password
- Impossible to find an option in Vanilla OS to change this behavior
- At every reboot, the problem remain.

On what version of Vanilla OS this happens?
2.0 image # 100 | 08/01/2024
Unreleased

Additional Information
This issue was started in Vanilla installer repo first because I first focus on the first reboot and didn't check if it was possible to change this behavior on new reboot (because reboot was not possible on previous alpha version of Orchid :-) https://github.com/Vanilla-OS/vanilla-installer/issues/262

**Comment by taukakao** [comment] 2024-01-12 19:52
Duplicate of https://github.com/Vanilla-OS/Albius/issues/40

**Closed by taukakao** 2024-01-12 19:52 UTC
Labels: duplicate
