### ISSUE TITLE
ABRoot transactions on Orchid fail with chroot "Exec format error"

### ISSUE THREAD

**Issue by PilotGuy772** [Vanilla-OS/ABRoot#188] opened 2024-01-05 23:57 UTC
When trying to add packages using `abroot pkg add` and then `abroot pkg apply` from the vso-pico shell, `abroot pkg apply` consistently fails right after it finishes syncing with the error `chroot: failed to run command '/bin/sh': Exec format error`. 

This consistently happens right after the syncing step. The same thing happens with `abroot upgrade`, but doesn't seem to affect `kargs`, `update-initramfs`, or others. Here is an excerpt of the command's output with `-v`:
```
Syncing var/spool/cups/tmp/                 [147038/147038] █████████████████████████████████████████████████ 100% | 12s
(Verbose) [Stage 5] -------- ABSystemRunOperation
(Verbose) ABImage.WriteTo: running...
(Verbose) ABImage.WriteTo: successfully wrote abimage.abr to /part-future/abimage-new.abr
(Verbose) ABSystem.RemoveStageFile: stage file removed
(Verbose) [Stage 6] -------- ABSystemRunOperation
(Verbose) ABSystem.GenerateFstab: generating fstab
(Verbose) ABSystem.GenerateFstab: fstab generated
(Verbose) ABSystem.GenerateCrypttab: generating crypttab
(Verbose) ABSystem.GenerateCrypttab: Adding vos--var-var to crypttab
(Verbose) ABSystem.GenerateSystemdUnits: generating units
(Verbose) ABSystem.GenerateSystemdUnits: generating unit for /home
(Verbose) ABSystem.GenerateSystemdUnits: generating unit for /opt
(Verbose) ABSystem.GenerateSystemdUnits: generating unit for /.system/usr/lib/locale
(Verbose) ABSystem.GenerateSystemdUnits: generating unit for /.system/etc
(Verbose) ABSystem.GenerateSystemdUnits: units generated
(Verbose) ApplyInImageForRoot: running...
(Verbose) FindImageWithLabel: running...
(Verbose) [Stage 7] -------- ABSystemRunOperation
(Verbose) NewChroot: running...
(Verbose) Chroot.Execute: running...
(Verbose) Chroot.Execute: running command: mount --bind / /
chroot: failed to run command ‘/bin/sh’: Exec format error
(Verbose) Chroot.Execute:err: exit status 126
```

Anybody else have this issue?

**Comment by mirkobrombin** [comment] 2024-04-28 09:30
Can't reproduce. I think this got fixed by one of the many changes since this Jan. Can you try to replicate with a recent build?

**Comment by taukakao** [comment] 2024-07-25 01:30
I'm gonna close this as it might be fixed. 
Feel free to reopen if it happens again

**Closed by taukakao** 2024-07-25 01:30 UTC
Labels: bug, waiting response
